version: '3.8'

services:
  backend:
    build: ./backend-spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/medical_iot?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - medic-net

  frontend:
    build: ./frontend-dashboard
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - medic-net

  analytics:
    build: ./analytics-python
    ports:
      - "4242:4242"
    networks:
      - medic-net

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medical_iot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - medic-net

networks:
  medic-net:
    driver: bridge

volumes:
  mysql_data:
